// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrftIi5pviTMJ73SULSe5TJZEHqqD-Y58',
    appId: '1:882261605522:web:698bfb19d235d06fa37a4b',
    messagingSenderId: '882261605522',
    projectId: 'servy-app2-1702a',
    authDomain: 'servy-app2-1702a.firebaseapp.com',
    storageBucket: 'servy-app2-1702a.appspot.com',
    measurementId: 'G-GDRWGX6MJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBv5h7gK7LRXRVwEpukO2vnhXegGqTqaI',
    appId: '1:882261605522:android:10c6b9b01f009146a37a4b',
    messagingSenderId: '882261605522',
    projectId: 'servy-app2-1702a',
    storageBucket: 'servy-app2-1702a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXEia7APa3xqGMTVgRw0HIG6pD79Iv3oQ',
    appId: '1:882261605522:ios:e17750f6ac1ad92ca37a4b',
    messagingSenderId: '882261605522',
    projectId: 'servy-app2-1702a',
    storageBucket: 'servy-app2-1702a.appspot.com',
    iosBundleId: 'com.example.servyApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXEia7APa3xqGMTVgRw0HIG6pD79Iv3oQ',
    appId: '1:882261605522:ios:05bbd2a5210a4080a37a4b',
    messagingSenderId: '882261605522',
    projectId: 'servy-app2-1702a',
    storageBucket: 'servy-app2-1702a.appspot.com',
    iosBundleId: 'com.example.servyApp2.RunnerTests',
  );
}
